server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/carbon
    username: root
    password: 123456
  devtools:
    restart:
      enabled: true
      additional-exclude: src/main/java
      exclude: static/**
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 20MB
  mvc:
    throw-exception-if-no-handler-found: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    root: debug